# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: test page title
subtitle: test page subtitle
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  githab pages exampleの多言語対応テストです
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  webbigdata-jp


# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: contrast
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-polyglot

include:
  - _pages
future: true

logo: "/assets/images/logo2.png"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/llm_jp
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: https://github.com/llm-jp

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # author_profile: true
      # read_time: true
      # comments: true
      show_date: true
      # share: true
      # related: true

sass:
  quiet_deps: true

atom_feed:
  hide: true

languages: ["ja", "en", "zh"]
default_lang: "ja"
exclude_from_localization: ["assets/css", "assets/img"]
parallel_localization: true


